SELECT * FROM customer LIMIT 20

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount FROM customer
WHERE discount_applied='Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)


-- Q3. Which are the top 5 products with the highest average reveiw rating?
SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC),2) as "Average Product Rating" FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) desc
limit 5

-- Q4. Compare the average purchase amounts between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) AS "Total Customers",
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
from customer
GROUP BY subscription_status
ORDER BY avg_spend, total_revenue


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased ,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 else 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each  segment.
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END
	AS customer_segment
from customer
)

SELECT customer_segment, count(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as(
SELECT category, 
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC)AS item_rank
from customer
GROUP BY category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;